# Generated by Django 4.2.6 on 2023-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=350, upload_to='pics/', width_field=500),
        ),
    ]
